repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(gen|provider|cdktf.out)|\.lock
      - id: end-of-file-fixer
        exclude: ^(gen|provider|cdktf.out)|\.lock
      - id: check-json
        exclude: ^(provider|cdktf.out)
      - id: check-yaml
        exclude: ^(proto/.*?/kubernetes|provider|cdktf.out)
      - id: check-toml
        exclude: ^(gen|provider|cdktf.out)
      - id: check-shebang-scripts-are-executable
