repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(provider|cdktf.out|.local)/|\.lock|charts|/tf/
      - id: end-of-file-fixer
        exclude: ^(provider|cdktf.out|.local)/|\.lock|charts|/tf/
      - id: check-json
        exclude: ^(provider|cdktf.out|.local)/|/tf/
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
        exclude: ^(provider|cdktf.out|.local)/|charts|/tf/
      - id: check-toml
        exclude: ^(provider|cdktf.out|.local)/|charts|/tf/
      - id: check-shebang-scripts-are-executable
