repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml

  - repo: local
    hooks:
      - id: cue-fmt
        name: cue-fmt
        entry: bash -c 'for a in "$@"; do cue fmt --simplify "$a"; done' ''
        language: system
        files: '\.cue$'
        pass_filenames: true

  - repo: local
    hooks:
      - id: sh-fmt
        name: sh-fmt
        entry: shfmt -w
        language: system
        files: "^(bin|etc)/"
        pass_filenames: true

  - repo: local
    hooks:
      - id: pants-fmt
        name: pants-fmt
        entry: pants --owners-not-found-behavior=ignore fmt lint
        language: system
        pass_filenames: true
