schema = 3

[mod]
  [mod."cuelang.org/go"]
    version = "v0.4.3"
    hash = "sha256-i9wampQA4Fnjfzce91SNb76WD3iEQir8VP66WJdTNGY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.2.0"
    hash = "sha256-JaGYNQwDxFCsLwzYVoJY4RUpP4dtiRlV14t2dVAg4oQ="
  [mod."github.com/andybalholm/brotli"]
    version = "v1.0.4"
    hash = "sha256-gAnPRdGP4yna4hiRIEDyBtDOVJqd7RU27wlPu96Rdf8="
  [mod."github.com/aws/constructs-go/constructs/v10"]
    version = "v10.1.225"
    hash = "sha256-UGewNiSFddcy2ne4Kq9YC4sQEfY0WIY18Z9mrcP9dyU="
  [mod."github.com/aws/jsii-runtime-go"]
    version = "v1.73.0"
    hash = "sha256-l+jHHwQSFcylR0dIJMze0CSWzoeCN1NTaboQ0AgBHKY="
  [mod."github.com/cdktf/cdktf-provider-aws-go/aws/v12"]
    version = "v12.0.1"
    hash = "sha256-aAen5kWLdylnh7uU6B20cMnf0pxFFdDiCSDst4B2090="
  [mod."github.com/cdktf/cdktf-provider-tfe-go/tfe/v5"]
    version = "v5.0.0"
    hash = "sha256-XRNRLoHIipVBBtzRZgNNSKc4VxqiSvNND+S9fPxgtos="
  [mod."github.com/cockroachdb/apd/v2"]
    version = "v2.0.1"
    hash = "sha256-LVk+EVXgGvqzKkYPnayabbRUf0iaq6oVu5JJ1SVsQyg="
  [mod."github.com/emicklei/proto"]
    version = "v1.6.15"
    hash = "sha256-dbBXi/fukrCvfxqnYK0ikNlodpgUoknh1xX4fqjHLE4="
  [mod."github.com/gofiber/fiber/v2"]
    version = "v2.40.1"
    hash = "sha256-JvKFGbjUcKolP8Tf1FCWK+4SgeG7TuPQN5ydkEI0k4I="
  [mod."github.com/golang/glog"]
    version = "v0.0.0-20160126235308-23def4e6c14b"
    hash = "sha256-YDyL9TRikSXHSrYtITVA/ovYIYrdnZGym14XnslAYkk="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/hashicorp/terraform-cdk-go/cdktf"]
    version = "v0.15.0"
    hash = "sha256-7zzU7PXyvocDyWaPguFlrojzsgZzDbDBEUUUPD4N8tw="
  [mod."github.com/klauspost/compress"]
    version = "v1.15.9"
    hash = "sha256-ctPxlVq0c/SoNPVsP66RjxUjTHys3diW2Apxjyc9WdE="
  [mod."github.com/kr/text"]
    version = "v0.2.0"
    hash = "sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.16"
    hash = "sha256-YMaPZvShDfA98vqw1+zWWl7M1IT4nHPGBrAt7kHo8Iw="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.14"
    hash = "sha256-O3QdxqAcJgQ+HL1v8oBA4iKBwJ2AlDN+F464027hWMU="
  [mod."github.com/mpvl/unique"]
    version = "v0.0.0-20150818121801-cbe035fff7de"
    hash = "sha256-kWdg8qhWQem2xCzwQKbQ0dmwA8D5Zwe6owPIgSMSIB4="
  [mod."github.com/niemeyer/pretty"]
    version = "v0.0.0-20200227124842-a10e7caefd8e"
    hash = "sha256-m2D7hWZrDst0rb91lmjSuNrzBQbmQ0Oe2UOp3wn8qso="
  [mod."github.com/pkg/errors"]
    version = "v0.8.1"
    hash = "sha256-oe3iddfoLRwpC3ki5fifHf2ZFprtg99iNak50shiuDw="
  [mod."github.com/protocolbuffers/txtpbfmt"]
    version = "v0.0.0-20201118171849-f6a6b3f636fc"
    hash = "sha256-K8yi3DPsjlCMKw6xH9Fp3uBgWySTT4NUQBqIw51q/4E="
  [mod."github.com/rivo/uniseg"]
    version = "v0.2.0"
    hash = "sha256-GLj0jiGrT03Ept4V6FXCN1yeZ/b6PpS3MEXK6rYQ8Eg="
  [mod."github.com/valyala/bytebufferpool"]
    version = "v1.0.0"
    hash = "sha256-I9FPZ3kCNRB+o0dpMwBnwZ35Fj9+ThvITn8a3Jr8mAY="
  [mod."github.com/valyala/fasthttp"]
    version = "v1.41.0"
    hash = "sha256-lV9FP7GjnQk/kJACE9l5CZ/8kzORdNpYS5lPokEYrZM="
  [mod."github.com/valyala/tcplisten"]
    version = "v1.0.0"
    hash = "sha256-aP0CrNH6UNRMhzgA2NgPwKyZs6xry5aDlZnLgGuHZbs="
  [mod."github.com/yuin/goldmark"]
    version = "v1.4.13"
    hash = "sha256-GVwFKZY6moIS6I0ZGuio/WtDif+lkZRfqWS6b4AAJyI="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20210508222113-6edffad5e616"
    hash = "sha256-U4o4PZ8KRpwbUN+E0VwewWNCiK5OGeBIpAMLJEbO9Ng="
  [mod."golang.org/x/mod"]
    version = "v0.7.0"
    hash = "sha256-ur4ld/ZtS6fnjLpHje0i00buolCTxVDH/HBJPfTj1Yc="
  [mod."golang.org/x/net"]
    version = "v0.3.0"
    hash = "sha256-OI4gNVzMPINNmOYqYbZ/+UciR4HGqwHJJSAy8bbvc88="
  [mod."golang.org/x/sys"]
    version = "v0.3.0"
    hash = "sha256-TIHhfYbZ99sCU1ZMikxwomXH5AEtD/lA1VMMW+UAhbU="
  [mod."golang.org/x/text"]
    version = "v0.5.0"
    hash = "sha256-ztH+xQyM/clOcQl+y/UEPcfNKbc3xApMbEPDDZ9up0o="
  [mod."golang.org/x/tools"]
    version = "v0.4.0"
    hash = "sha256-4AM7kqZ61pd2azkXJu9e/Djb/NRsm5waW0AWOXLVUWg="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20200227125254-8fa46927fb4f"
    hash = "sha256-nGV66SlDrpDfhkzlr9h52JybsCioW3ix5bKmbkEfoDs="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
