get:
	earthly +get
	rsync -ia provider.new/. provider/.
	rm -rf provider.new

venv:
	cd 3rdparty/python && poetry install
	
plan:
	earthly +plan --stack=demo

show:
	earthly +show --stack=demo

apply:
	earthly --push +apply --stack=demo
