python_sources(
    skip_black=True,
    skip_flake8=True,
    skip_isort=True,
    skip_docformatter=True,
    dependencies=[":jsii"],
)

resource(
    name="jsii",
    source="hashicorp_boundary@0.0.0.jsii.tgz",
)
