python_sources(
    skip_black=True,
    skip_isort=True,
    skip_docformatter=True,
    dependencies=[":jsii"],
    resolve="defn",
)

resource(
    name="jsii",
    source="cloudflare_cloudflare@0.0.0.jsii.tgz",
)
