VERSION --shell-out-anywhere --use-chmod --use-host-command --earthly-version-arg --use-copy-link 0.6

SYNTH:
    COMMAND
    ARG stack
    COPY cdktf.json .
    RUN ~/bin/e cdktf synth
    SAVE ARTIFACT cdktf.out/stacks/${stack}/cdk.tf.json AS LOCAL cdktf.out/stacks/${stack}/

INIT:
    COMMAND
    ARG stack
    COPY cdktf.out/stacks/${stack}/cdk.tf.json cdktf.out/stacks/${stack}/
    RUN --mount=type=cache,target=/home/ubuntu/.terraform.d/plugin-cache-buildkit \
        sudo chown -v ubuntu:ubuntu /home/ubuntu/.terraform.d/plugin-cache-buildkit
    RUN --mount=type=cache,target=/home/ubuntu/.terraform.d/plugin-cache-buildkit \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        cd cdktf.out/stacks/${stack} && ~/bin/e env TF_PLUGIN_CACHE_DIR=/home/ubuntu/.terraform.d/plugin-cache-buildkit terraform init
    RUN --mount=type=cache,target=/home/ubuntu/.terraform.d/plugin-cache-buildkit \
        mkdir -p /home/ubuntu/.terraform.d/plugin-cache && rsync -ia /home/ubuntu/.terraform.d/plugin-cache-buildkit/. /home/ubuntu/.terraform.d/plugin-cache/.
    RUN \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        cd cdktf.out/stacks/${stack} && ~/bin/e terraform init

EDIT:
    COMMAND
    ARG stack
    ARG cmd
    RUN --push --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix  --secret AWS_SECRET_ACCESS_KEY_helix \
        --secret AWS_ACCESS_KEY_ID_coil   --secret AWS_SECRET_ACCESS_KEY_coil \
        --secret AWS_ACCESS_KEY_ID_curl   --secret AWS_SECRET_ACCESS_KEY_curl \
        --secret AWS_ACCESS_KEY_ID_gyre   --secret AWS_SECRET_ACCESS_KEY_gyre \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && ~/bin/e ${cmd}'

PLAN:
    COMMAND
    ARG stack
    RUN --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        --secret DIGITALOCEAN_TOKEN --secret BUILDKITE_API_TOKEN --secret GITHUB_TOKEN --secret CLOUDFLARE_API_KEY \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix  --secret AWS_SECRET_ACCESS_KEY_helix \
        --secret AWS_ACCESS_KEY_ID_coil   --secret AWS_SECRET_ACCESS_KEY_coil \
        --secret AWS_ACCESS_KEY_ID_curl   --secret AWS_SECRET_ACCESS_KEY_curl \
        --secret AWS_ACCESS_KEY_ID_gyre   --secret AWS_SECRET_ACCESS_KEY_gyre \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && ~/bin/e terraform plan -out=.plan'
    SAVE ARTIFACT cdktf.out/stacks/${stack}/.plan AS LOCAL cdktf.out/stacks/${stack}/

SHOW:
    COMMAND
    ARG stack
    COPY cdktf.out/stacks/${stack}/.plan cdktf.out/stacks/${stack}/
    RUN --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        --secret DIGITALOCEAN_TOKEN --secret BUILDKITE_API_TOKEN --secret GITHUB_TOKEN --secret CLOUDFLARE_API_KEY \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix  --secret AWS_SECRET_ACCESS_KEY_helix \
        --secret AWS_ACCESS_KEY_ID_coil   --secret AWS_SECRET_ACCESS_KEY_coil \
        --secret AWS_ACCESS_KEY_ID_curl   --secret AWS_SECRET_ACCESS_KEY_curl \
        --secret AWS_ACCESS_KEY_ID_gyre   --secret AWS_SECRET_ACCESS_KEY_gyre \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && ~/bin/e terraform show .plan'

IMPORT:
    COMMAND
    ARG stack
    RUN --push --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix  --secret AWS_SECRET_ACCESS_KEY_helix \
        --secret AWS_ACCESS_KEY_ID_coil   --secret AWS_SECRET_ACCESS_KEY_coil \
        --secret AWS_ACCESS_KEY_ID_curl   --secret AWS_SECRET_ACCESS_KEY_curl \
        --secret AWS_ACCESS_KEY_ID_gyre   --secret AWS_SECRET_ACCESS_KEY_gyre \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && i="`aws sts get-caller-identity --query Account --output text`" && ~/bin/e terraform import aws_organizations_account.${stack} ${i}'
    RUN --push --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix  --secret AWS_SECRET_ACCESS_KEY_helix \
        --secret AWS_ACCESS_KEY_ID_coil   --secret AWS_SECRET_ACCESS_KEY_coil \
        --secret AWS_ACCESS_KEY_ID_curl   --secret AWS_SECRET_ACCESS_KEY_curl \
        --secret AWS_ACCESS_KEY_ID_gyre   --secret AWS_SECRET_ACCESS_KEY_gyre \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && i="`aws sts get-caller-identity --query Account --output text`" && o="`aws organizations describe-account --account-id "${i}" | jq -r .Account.Arn | cut -d/ -f2`" && ~/bin/e terraform import aws_organizations_organization.organization ${o}'

CONFIG:
    COMMAND
    ARG stack
    ARG region
    ARG sso_region
    RUN --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix  --secret AWS_SECRET_ACCESS_KEY_helix \
        --secret AWS_ACCESS_KEY_ID_coil   --secret AWS_SECRET_ACCESS_KEY_coil \
        --secret AWS_ACCESS_KEY_ID_curl   --secret AWS_SECRET_ACCESS_KEY_curl \
        --secret AWS_ACCESS_KEY_ID_gyre   --secret AWS_SECRET_ACCESS_KEY_gyre \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && i="`aws sts get-caller-identity --query Account --output text`" && ~/bin/e env region=${region} sso_region=${sso_region} sso_url=${sso_url} name=${stack} awsconfig > config'
    SAVE ARTIFACT config AS LOCAL cdktf.out/stacks/${stack}/.aws/config

APPLY:
    COMMAND
    ARG stack
    COPY cdktf.out/stacks/${stack}/.plan cdktf.out/stacks/${stack}/
    RUN --push --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        --secret DIGITALOCEAN_TOKEN --secret BUILDKITE_API_TOKEN --secret GITHUB_TOKEN --secret CLOUDFLARE_API_KEY \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix  --secret AWS_SECRET_ACCESS_KEY_helix \
        --secret AWS_ACCESS_KEY_ID_coil   --secret AWS_SECRET_ACCESS_KEY_coil \
        --secret AWS_ACCESS_KEY_ID_curl   --secret AWS_SECRET_ACCESS_KEY_curl \
        --secret AWS_ACCESS_KEY_ID_gyre   --secret AWS_SECRET_ACCESS_KEY_gyre \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && ~/bin/e terraform apply .plan'
