VERSION --shell-out-anywhere --use-chmod --use-host-command --earthly-version-arg --use-copy-link 0.6

INIT:
    COMMAND
    ARG stack
    COPY cdktf.json .
    RUN ~/bin/e cdktf synth
    RUN --mount=type=cache,target=/home/ubuntu/.terraform.d/plugin-cache-buildkit \
        sudo chown -v ubuntu:ubuntu /home/ubuntu/.terraform.d/plugin-cache-buildkit
    RUN --mount=type=cache,target=/home/ubuntu/.terraform.d/plugin-cache-buildkit \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        cd cdktf.out/stacks/${stack} && ~/bin/e env TF_PLUGIN_CACHE_DIR=/home/ubuntu/.terraform.d/plugin-cache-buildkit terraform init
    RUN --mount=type=cache,target=/home/ubuntu/.terraform.d/plugin-cache-buildkit \
        mkdir -p /home/ubuntu/.terraform.d/plugin-cache && rsync -ia /home/ubuntu/.terraform.d/plugin-cache-buildkit/. /home/ubuntu/.terraform.d/plugin-cache/.
    RUN \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        cd cdktf.out/stacks/${stack} && ~/bin/e terraform init

EDIT:
    COMMAND
    ARG stack
    ARG cmd
    RUN --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix --secret AWS_SECRET_ACCESS_KEY_helix \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && ~/bin/e ${cmd}'

IMPORT:
    COMMAND
    ARG stack
    RUN --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix --secret AWS_SECRET_ACCESS_KEY_helix \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && i="`aws sts get-caller-identity --query Account --output text`" && ~/bin/e terraform import aws_organizations_account.${stack} ${i}'
    RUN --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix --secret AWS_SECRET_ACCESS_KEY_helix \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && i="`aws sts get-caller-identity --query Account --output text`" && o="`aws organizations describe-account --account-id "${i}" | jq -r .Account.Arn | cut -d/ -f2`" && ~/bin/e terraform import aws_organizations_organization.organization ${o}'

PLAN:
    COMMAND
    ARG stack
    RUN --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io --secret DIGITALOCEAN_TOKEN --secret BUILDKITE_API_TOKEN --secret GITHUB_TOKEN --secret CLOUDFLARE_API_KEY \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix --secret AWS_SECRET_ACCESS_KEY_helix \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && ~/bin/e terraform plan -out=.plan'
    SAVE ARTIFACT cdktf.out/stacks/${stack}/.plan AS LOCAL cdktf.out/stacks/${stack}/
    SAVE ARTIFACT cdktf.out/stacks/${stack}/.terraform.lock.hcl AS LOCAL cdktf.out/stacks/${stack}/

SHOW:
    COMMAND
    ARG stack
    COPY cdktf.out/stacks/${stack}/.plan cdktf.out/stacks/${stack}/.plan
    COPY cdktf.out/stacks/${stack}/.terraform.lock.hcl cdktf.out/stacks/${stack}/.terraform.lock.hcl
    RUN --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io --secret DIGITALOCEAN_TOKEN --secret BUILDKITE_API_TOKEN --secret GITHUB_TOKEN --secret CLOUDFLARE_API_KEY \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix --secret AWS_SECRET_ACCESS_KEY_helix \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && ~/bin/e terraform show .plan'

APPLY:
    COMMAND
    ARG stack
    COPY cdktf.out/stacks/${stack}/.plan cdktf.out/stacks/${stack}/.plan
    COPY cdktf.out/stacks/${stack}/.terraform.lock.hcl cdktf.out/stacks/${stack}/.terraform.lock.hcl
    RUN --push --no-cache \
        --secret TFE_TOKEN --secret TF_TOKEN_app_terraform_io --secret DIGITALOCEAN_TOKEN --secret BUILDKITE_API_TOKEN --secret GITHUB_TOKEN --secret CLOUDFLARE_API_KEY \
        --secret AWS_ACCESS_KEY_ID_spiral --secret AWS_SECRET_ACCESS_KEY_spiral \
        --secret AWS_ACCESS_KEY_ID_helix --secret AWS_SECRET_ACCESS_KEY_helix \
        bash -c 'a=AWS_ACCESS_KEY_ID_${stack} b=AWS_SECRET_ACCESS_KEY_${stack} && export AWS_ACCESS_KEY_ID="${!a}" AWS_SECRET_ACCESS_KEY="${!b}" && cd cdktf.out/stacks/${stack} && ~/bin/e terraform apply .plan'
