VERSION --shell-out-anywhere --use-chmod --use-host-command --earthly-version-arg --use-copy-link 0.6

build:
    FROM ubuntu
    WORKDIR /work
    COPY html/* .
    RUN --no-cache date
    SAVE ARTIFACT ./* AS LOCAL dist/