apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra
  labels:
    app: infra
spec:
  selector:
    matchLabels:
      app: infra
  template:
    metadata:
      labels:
        app: infra
    spec:
      containers:
      - name: infra
        image: infra
