schema = 3

[mod]
  [mod."github.com/labstack/echo/v4"]
    version = "v4.9.1"
    hash = "sha256-Wq2SowGOSDEDBsVuOtR/FVoSHbXXLBOxOxnb+letOG0="
  [mod."github.com/labstack/gommon"]
    version = "v0.4.0"
    hash = "sha256-xISAIJEu2xh0hoWsORbgjnz3rDK3ft3hrvmxt0wfHVw="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.16"
    hash = "sha256-YMaPZvShDfA98vqw1+zWWl7M1IT4nHPGBrAt7kHo8Iw="
  [mod."github.com/valyala/bytebufferpool"]
    version = "v1.0.0"
    hash = "sha256-I9FPZ3kCNRB+o0dpMwBnwZ35Fj9+ThvITn8a3Jr8mAY="
  [mod."github.com/valyala/fasttemplate"]
    version = "v1.2.1"
    hash = "sha256-+VtRavE4b+C8CSzQUQoN5QnVwfeepQUGfBI+8VasjLg="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220214200702-86341886e292"
    hash = "sha256-Mg/1EHDCtRLt1hyPp836ONo3p1UGtne6nxKPY0TdX6I="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20220906165146-f3363e06e74c"
    hash = "sha256-WlfqWGXDNWLFBuIqoGkJWNcUJKys+h9WpkG4IW3EYtU="
  [mod."golang.org/x/sys"]
    version = "v0.1.0"
    hash = "sha256-nZbEJ/2PuWrDLD4ujeVvcFGoIsfVoIH/Lcp4FjD7hpU="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
